name: Generate Video Script (9:16)

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Video topic (必填)"
        required: true
        type: string
      audience:
        description: "Target audience (可选)"
        required: false
        type: string
      duration_minutes:
        description: "Target duration in minutes (可选)"
        required: false
        type: number
        default: 1
      style:
        description: "Tone/style (可选)"
        required: false
        type: string
      openai_model:
        description: "Model name"
        required: false
        default: deepseek-chat
        type: string
      dry_run:
        description: "If true, generate file but do NOT open a PR"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==1.43.0 python-slugify==8.0.4 pyyaml==6.0.2

      - name: Generate script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        run: |
          python scripts/generate_script.py \
            --topic "${{ inputs.topic }}" \
            --audience "${{ inputs.audience }}" \
            --duration "${{ inputs.duration_minutes }}" \
            --style "${{ inputs.style }}" \
            --model "${{ inputs.openai_model }}" \
            --dry-run "${{ inputs.dry_run }}"

      - name: Create Pull Request with generated script
        if: ${{ !inputs.dry_run }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add generated video script"
          title: "feat: add video script - ${{ inputs.topic }}"
          body: "Automated script generation via workflow."
          branch: "content/script/${{ github.run_id }}"
          delete-branch: true